### ISSUE TITLE
Application architecture

### ISSUE THREAD

**Issue by wingsofovnia** [wingsofovnia/p2p-group27-onion#15]
"What type of process architecture you have? (single threaded/multi-threaded/ multiprocess,
etc..). Do you use event loops or not?" - Interim Report Checklist

**Comment by wingsofovnia** [comment]
The initial decision is using event loops and single threaded environment for its simplicity = easy to develop, maintain and debug.

Netty architecture is described here: http://ayedo.github.io/netty/2013/06/19/what-is-netty.html
We can take some fancy illustrations and description from it. For example, this pic describes message process architecture in very simple and straightforward:
![image](https://cloud.githubusercontent.com/assets/5632544/26764833/f8aa6dda-496e-11e7-8aba-d2709073087e.png)

**Comment by Microhive** [comment]
Application Architecture

We are looking into creating a multi-threaded architecture, in which incoming requests are intercepted by a single thread (the Selector), queued, and subsequently processed asynchronously by threads (Thread Handlers) from a thread pool. To achieved this goal, we take advantage of the Netty framework. One of its main benefits is the concept of pipelines for events; in which a task can be sequentially processed in multiple steps. This is a powerful concept considering the application in question and the data being transported; layered packaged data that must be and processed in multiple steps. The end result is a more secure, non-blocking, high performant, and scalable solution. 

![](http://ayedo.github.io/img/selector.png)


The network library process architecture is as follows, in which the handlers illustrate the sequence of a possible pipeline.

![](https://cloud.githubusercontent.com/assets/5632544/26764833/f8aa6dda-496e-11e7-8aba-d2709073087e.png)

**Comment by Microhive** [comment]
1. Architecture
https://www.sharelatex.com/project/593516786e5eb74879d65eaa
