### ISSUE TITLE
Modules running on different peers auth

### ISSUE THREAD

**Issue by wingsofovnia** [wingsofovnia/p2p-group27-onion#18]
How do your modules running on different peers authenticate? This is needed because there could be another service running on the port allocated for your module on the remote peer and your module needs to verify that it is talking to that correct module on the remote peer?

**Comment by Microhive** [comment]
Notes from researching Onion Authentication. 

Onion Authentication only communicates with the Onion Forwarding Module. Onion Forwarding will forward any incoming message for the Onion Authentication module with the correct authentication message types, e.g. "AUTH SESSION HS1". 

Authentication message types will contain a payload in their messages. We don't care much about this, as we are only interested in analyzing the first part of any packet message (size, message type, reserved, request id) and any Onion Forwarding message types in the range of 560-599.

This practically means that P2P communications are essentially handled by the Onion Forwarding modules between peers and only Onion Authentication message types are forwarded to a node's Onion Authentication module for processing.

**Comment by wingsofovnia** [comment]
2. Onion Routing
https://www.sharelatex.com/project/593516786e5eb74879d65eaa
